blueprints/showcase/views.py
from flask import Blueprint, render_template, request
import os
import zipfile
from flask import flash, request, send_file

from models.song import Song

bp = Blueprint(
    "showcase",
    __name__,
    url_prefix="/showcase",
    template_folder="templates",
)


@bp.route("/", methods=["GET"])
def showcase():
    songs = Song.query.all()
    print(songs)
    return render_template("showcase.html", songs=songs)


@bp.route("/download", methods=["GET"])
def download():
    title = request.args.get("title")

    # The download logic is the same, except you need to append any filter params appropriately
    # Retrieve the song with the given id from the database
    song = Song.query.where(Song.title == title.lower()).first()
    if song is None:
        return flash("Sorry, we couldn't find that song!")

    if request.args.get("part"):
        title += "_" + request.get.args("part")
        # Eventually there will be more keys available...
        match request.get.args("part"):
            case "C":
                return send_file(song.c_sheet_music, as_attachment=True)
            case "Bb":
                return send_file(song.bb_sheet_music, as_attachment=True)
            case "Eb":
                return send_file(song.eb_sheet_music, as_attachment=True)
            case "Bass":
                return send_file(song.bass_sheet_music, as_attachment=True)

    # Download a zip of the files for the row given the paths
    zip_path = f"/tmp/{song.title}.zip"
    with zipfile.ZipFile(zip_path, "w") as zip_file:
        zip_file.write(song.audio, os.path.basename(song.audio))
        zip_file.write(song.c_sheet_music, os.path.basename(song.c_sheet_music))
        if song.bb_sheet_music:
            zip_file.write(song.bb_sheet_music, os.path.basename(song.bb_sheet_music))
        if song.eb_sheet_music:
            zip_file.write(song.eb_sheet_music, os.path.basename(song.eb_sheet_music))
        zip_file.write(song.bass_sheet_music, os.path.basename(song.bass_sheet_music))
    return send_file(zip_path, as_attachment=True)

blueprints/showcase/templates/poster.html
<div class="rounded overflow-hidden shadow-md">
  <!-- Only the desired sheet music is shown, but there is text notating the parts included -->
  <embed
    src="{{ url_for('showcase.download', title={{filename}}) }}"
    alt="The sheet music for the song"
  />
  <h1 class="font-extrabold text-lg text-center">{{title}}</h1>
  {% partsString = part + ", " for part in {{parts}} %}
  <h2 class="text-sm text-center">Parts for {{partsString[0:-2]}}</h2>
</div>

blueprints/showcase/templates/showcase.html
{% extends 'base.html' %} {% block title %} Jazzle {% endblock %} {% block body
%}
<div class="flex flex-col min-h-screen">
  <div class="h-8"></div>
  <!-- The search input -->
  <div class="flex flex-row justify-center" id="search">
    <input
      class="border-2"
      hx-get="/search"
      hx-target="#results"
      placeholder="Find a standard!"
    />
    <!-- <h2
      hx-get="/advanced_search"
      hx-target="#advanced_search"
      class="font-extrabold color-slate-200"
    >
      Advanced Search
    </h2> -->
  </div>
  <!-- The search results; posters with the song data returned by backend -->
  <div
    id="results"
    class="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-4 pad-4"
  >
    {% for song in songs %} {% if song.selected %}
    <div class="bg-white p-4 shadow-md">
      <h2 class="bg-slate-300 text-center text-lg font-bold">
        {{ song.title }}
      </h2>
      <div class="flex justify-center">
        <img src="/../{{song.poster}}" class="w-64 h-64 object-cover" />
      </div>
      <div class="flex justify-center mt-4">
        {% if song.c_sheet_music %}
        <button
          class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded"
        >
          C Sheet Music
        </button>
        {% endif %} {% if song.bb_sheet_music %}
        <button
          class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded ml-2"
        >
          Bb Sheet Music
        </button>
        {% endif %}
      </div>
      <div class="flex justify-center mt-4">
        {% if song.eb_sheet_music %}
        <button
          class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded"
        >
          Eb Sheet Music
        </button>
        {% endif %} {% if song.bass_sheet_music %}
        <button
          class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded ml-2"
        >
          Bass Sheet Music
        </button>
        {% endif %}
      </div>
      <div class="flex justify-center mt-4">
        {% if song.audio %}
        <button
          class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded"
        >
          Audio
        </button>
        {% endif %}
      </div>
    </div>

    {% endif %} {% endfor %}
  </div>
  {% endblock %}
</div>